FROM pgvector/pgvector:pg16

ENV PORT=5432
ENV POSTGRES_USER=affine
ENV POSTGRES_PASSWORD=changeme
ENV POSTGRES_DB=affine
ENV POSTGRES_INITDB_ARGS="--data-checksums"
ENV POSTGRES_HOST_AUTH_METHOD=scram-sha-256
ENV PGDATA=/var/lib/postgresql/data/pgdata
